const data=[
  {
    "login": "ragOP",
    "id": 84832906,
    "node_id": "MDQ6VXNlcjg0ODMyOTA2",
    "avatar_url": "https://avatars.githubusercontent.com/u/84832906?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ragOP",
    "html_url": "https://github.com/ragOP",
    "followers_url": "https://api.github.com/users/ragOP/followers",
    "following_url": "https://api.github.com/users/ragOP/following{/other_user}",
    "gists_url": "https://api.github.com/users/ragOP/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ragOP/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ragOP/subscriptions",
    "organizations_url": "https://api.github.com/users/ragOP/orgs",
    "repos_url": "https://api.github.com/users/ragOP/repos",
    "events_url": "https://api.github.com/users/ragOP/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ragOP/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Raghib Najmi",
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": "Full Time Pubg player part time software Engineer ",
    "twitter_username": null,
    "public_repos": 24,
    "public_gists": 0,
    "followers": 0,
    "following": 4,
    "created_at": "2021-05-26T06:10:45Z",
    "updated_at": "2022-01-06T10:42:13Z"
  }
  ]
module.exports=data;
